theme: jekyll-theme-midnight
title: Techlahoma Living Room Series
logo: https://raw.githubusercontent.com/sgelbart/living-room-series/master/living-room-series.png
description: Watching a recorded Techlahoma talk each month, followed by Q&A with the speaker on Zoom.
